/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { StudentData } from "../../types";

const STATUS = {
  official: "公假",
  absent: "缺席",
  present: "出席",
};

const StudentListItem: React.FC<StudentData> = ({
  id,
  name_ch: name,
  name_en: enName,
  class: className,
  seat_no: seatNumber,
  status,
  statusColor,
  hasSettled,
}) => {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="rounded-md bg-zinc-800 overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex w-full justify-between text-left p-4"
      >
        <div className="w-2/12">{id}</div>
        <div className="w-5/12">
          {name} {enName}
        </div>
        <div className="w-1/12 text-center">{className}</div>
        <div className="w-2/12 text-center">{seatNumber}</div>
        <div className="flex items-center gap-1.5 w-2/12">
          <div className={`shrink-0 size-2 ${statusColor} rounded-full`} />
          <div>
            {STATUS[status as keyof typeof STATUS]}
            {status === "absent" && !hasSettled && (
              <span className="text-red-600"> (未处理)</span>
            )}
          </div>
        </div>
      </button>
      <div
        className={`bg-blue-500/10 transition-all px-4 ease-linear overflow-hidden ${
          expanded ? "py-4 max-h-48" : "py-0 max-h-0"
        }`}
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-1.5 w-2/12">
            <div className={`shrink-0 size-2 ${statusColor} rounded-full`} />
            <div>
              {STATUS[status as keyof typeof STATUS]}
              {status === "absent" && !hasSettled && (
                <span className="text-red-600"> (未处理)</span>
              )}
            </div>
          </div>
          <p>5, 6, 7 节</p>
        </div>
        <p className="mt-2">备注：电脑常识比赛筹委</p>
      </div>
    </div>
  );
};

export default StudentListItem;
