/**
 * This code was generated by Builder.io.
 */
import React from "react";

const StudentListHeader: React.FC = () => {
  return (
    <div className="flex border-b-2 font-medium border-zinc-700 p-4">
      <div className="w-2/12">学号</div>
      <div className="w-5/12">姓名</div>
      <div className="w-1/12 text-center">班级</div>
      <div className="w-2/12 text-center">座号</div>
      <div className="w-2/12">状态</div>
    </div>
  );
};

export default StudentListHeader;
