/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { StudentData } from "../../../../ManageAbsences/types";
import Information from "../sections/Information";
import Cleanliness from "../sections/Cleanliness";
import LeaveMatters from "../sections/LeaveMatters";

const StudentListItem: React.FC<StudentData> = ({
  id,
  name_ch: name,
  name_en: enName,
  class: className,
  seat_no: seatNumber,
  status,
  statusColor,
  hasSettled,
}) => {
  const [expanded, setExpanded] = useState(false);
  const [expandedButton, setExpandedButton] = useState("基本资料");
  return (
    <div className="rounded-md bg-zinc-800 overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex w-full justify-between text-left p-4"
      >
        <div className="w-2/12">{id}</div>
        <div className="w-5/12">
          {name} {enName}
        </div>
        <div className="w-1/12 text-center">{className}</div>
        <div className="w-2/12 text-center">{seatNumber}</div>
        <div className="flex items-center gap-1.5 w-2/12">
          <div className={`shrink-0 size-2 ${statusColor} rounded-full`} />
          <div>
            {status}
            {status === "absent" && !hasSettled && (
              <span className="text-red-600"> (未处理)</span>
            )}
          </div>
        </div>
      </button>
      {/* expanded */}
      <div
        className={`bg-blue-500/10 transition-all px-4 ease-linear overflow-visible flex flex-row ${
          expanded ? "py-4" : "py-0 max-h-0"
        }`}
      >
        <div className="w-[20%] bg-blue-500/20 flex flex-col gap-3 rounded-md p-3 ">
          <button
            className={`bg-blue-500/20 p-3 rounded-md text-slate-300 ${
              expandedButton === "基本资料" &&
              "bg-blue-500/40 text-slate-50 font-semibold"
            }`}
            onClick={() => setExpandedButton("基本资料")}
          >
            基本资料
          </button>
          <button
            className={`bg-blue-500/20 p-3 rounded-md text-slate-300 ${
              expandedButton === "请假事宜" &&
              "bg-blue-500/40 text-slate-50 font-semibold"
            }`}
            onClick={() => setExpandedButton("请假事宜")}
          >
            请假事宜
          </button>
          <button
            className={`bg-blue-500/20 p-3 rounded-md text-slate-300 ${
              expandedButton === "卫生检查" &&
              "bg-blue-500/40 text-slate-50 font-semibold"
            }`}
            onClick={() => setExpandedButton("卫生检查")}
          >
            卫生检查
          </button>
        </div>
        <div className="w-[80%]">
          {expandedButton === "基本资料" ? (
            <Information
              student={{
                name,
                enName,
                className,
                seatNumber,
                status,
                statusColor,
                hasSettled,
                id,
              }}
            />
          ) : expandedButton === "卫生检查" ? (
            <Cleanliness />
          ) : expandedButton === "请假事宜" ? (
            <LeaveMatters setExpanded={setExpanded} students={{ id }} />
          ) : null}
        </div>
      </div>
    </div>
  );
};

export default StudentListItem;
