/**
 * This code was generated by Builder.io.
 */
import React, { useEffect, useState } from "react";
import StudentList from "./components/StudentList";
import { StudentData } from "./types";
import StudentListHeader from "./components/StudentList/components/StudentListHeader";
import { Icon } from "@iconify/react/dist/iconify.js";
import { useCollection } from "react-firebase-hooks/firestore";
import { collection } from "firebase/firestore";
import { firestore } from "../../firebase.config";

const ManageAbsences: React.FC = () => {
  const [search, setSearch] = useState("");
  const [value, loading] = useCollection(collection(firestore, "students"));
  const [filteredData, setFilteredData] = useState<StudentData[]>();
  useEffect(() => {
    console.log(value?.docs.map((doc) => doc.data() as StudentData));
    setFilteredData(
      value?.docs
        .map((doc) => doc.data() as StudentData)
        .filter(
          (student) =>
            student.name_ch.toLowerCase().includes(search.toLowerCase()) ||
            student.name_en.toLowerCase().includes(search.toLowerCase()) ||
            student.class.toLowerCase().includes(search.toLowerCase())
        )
    );
  }, [search]);
  return (
    <>
      <div className="flex gap-5 px-5 py-4 mb-4 whitespace-nowrap rounded-lg bg-zinc-800/50">
        <label htmlFor="searchInput" className="sr-only">
          搜索学生
        </label>
        <input
          id="searchInput"
          type="text"
          placeholder="搜索学生..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="flex-auto my-auto bg-transparent outline-none placeholder-zinc-400 caret-znc-100"
        />
        <Icon icon="tabler:search" className="size-6 text-zinc-400" />
      </div>
      <StudentListHeader />
      <>
        {loading || !value ? (
          <div>Loading...</div>
        ) : filteredData ? (
          <StudentList students={filteredData} />
        ) : (
          <StudentList students={value.docs.map((doc) => doc.data()) as any} />
        )}
      </>
    </>
  );
};

export default ManageAbsences;
