/**
 * This code was generated by Builder.io.
 */
export interface StudentData {
  id: string;
  name_ch: string;
  name_en: string;
  class: string;
  seatNumber: string;
  status: string;
  statusColor: string;
  hasSettled?: boolean;
  seat_no: number;
}
