/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { useLocation } from "react-router-dom";
import { toLinkCase } from "../utils/string";

const NAMES = [
  {
    zh: "控制面板",
    en: "Dashboard",
    description: "An overview of the attendance status of all classes",
  },
  {
    zh: "学生资料",
    en: "Students Info",
    description: "View the Information of all students",
  },
  {
    zh: "处理出缺席事宜",
    en: "Manage Absences",
    description: "Manage the attendance status of all students",
  },
  {
    zh: "管理班级",
    en: "Manage Classes",
    description: "Manage the classes and students",
  },
  {
    zh: "出席统计",
    en: "Attendance Statistics",
    description: "View the statistics of the attendance status",
  },
  {
    zh: "登入",
    en: "Login",
    description: "Login to the system",
  },
];

const Header: React.FC = () => {
  const location = useLocation();

  return (
    <header>
      <h1 className="text-3xl font-semibold text-zinc-100 tracking-[3px] max-md:max-w-full">
        {
          NAMES.find((name) => location.pathname.includes(toLinkCase(name.en)))
            ?.zh
        }{" "}
        {
          NAMES.find((name) => location.pathname.includes(toLinkCase(name.en)))
            ?.en
        }
      </h1>
      <p className="mt-2 mb-6 text-base tracking-wide text-zinc-400 max-md:max-w-full">
        {
          NAMES.find((name) => location.pathname.includes(toLinkCase(name.en)))
            ?.description
        }
      </p>
    </header>
  );
};

export default Header;
