/**
 * This code was generated by Builder.io.
 */
import { Icon } from "@iconify/react/dist/iconify.js";
import React from "react";

const SearchBar: React.FC = () => {
  return (
    <div className="flex gap-5 px-5 py-4 mb-4 whitespace-nowrap rounded-lg bg-zinc-800/50">
      <label htmlFor="searchInput" className="sr-only">
        搜索学生
      </label>
      <input
        id="searchInput"
        type="text"
        placeholder="搜索学生..."
        className="flex-auto my-auto bg-transparent outline-none placeholder-zinc-400 caret-znc-100"
      />
      <Icon icon="tabler:search" className="size-6 text-zinc-400" />
    </div>
  );
};

export default SearchBar;
