/**
 * This code was generated by Builder.io.
 */
import React, { useContext } from "react";
import SidebarItem from "./SidebarItem";
import { Icon } from "@iconify/react/dist/iconify.js";
import { signOut } from "../../firebase.config";
import AppContext from "../../AppContext";

const sidebarItems = [
  {
    icon: "uil:apps",
    title: "控制面板",
    subtitle: "Dashboard",
  },

  {
    icon: "uil:users-alt",
    title: "管理班级",
    subtitle: "Manage Classes",
    role: "form_teacher",
  },
  {
    icon: "uil:file-alt",
    title: "处理出缺席事宜",
    subtitle: "Manage Absences",
    role: "displin",
  },
  {
    icon: "uil:info-circle",
    title: "学生资料",
    subtitle: "Students Info",
  },
  {
    icon: "uil:chart-bar",
    title: "出缺席统计",
    subtitle: "Attendance Statistics",
    role: "displin",
  },
  {
    icon: "uil:sign-out-alt",
    title: "登出",
    subtitle: "Log Out",
    isLogout: true,
  },
];

const Sidebar: React.FC = () => {
  const { userData, navigate } = useContext<any>(AppContext);
  console.log(userData);

  return (
    <aside className="flex flex-col shrink-0 w-3/12 bg-zinc-800/50 py-8 h-100">
      <div className="flex flex-col items-center pl-6 text-white max-md:pl-5">
        <div className="flex gap-2.5 items-center self-stretch font-semibold">
          <Icon icon="tabler:school" className="size-8" />
          <div className="flex flex-col">
            <div className="tracking-widest">新山宽柔中学</div>
            <div className="mt-1.5 text-xs tracking-wider">
              Foon Yew High School
            </div>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://th.bing.com/th/id/OIP.XsiBnCkyrnMFagbVrcr8XQAAAA?rs=1&pid=ImgDetMain"
          alt="User profile"
          referrerPolicy="no-referrer"
          className="mt-14 w-20 rounded-full aspect-square max-md:mt-10"
        />
        <div className="mt-6 text-2xl tracking-[2.64px] font-semibold">
          {userData?.ch_name}
        </div>
        <div className="mt-4 text-sm tracking-widest text-zinc-400">
          {userData?.role === "form_teacher"
            ? `${userData.class} 班主任`
            : "训导处老师"}
        </div>
      </div>
      <nav className="w-full mt-12">
        {sidebarItems.map(
          (item, index) =>
            (item.role === undefined || item.role === userData.role) && (
              <SidebarItem key={index} {...item} />
            )
        )}
      </nav>
    </aside>
  );
};

export default Sidebar;
