/**
 * This code was generated by Builder.io.
 */
import React, { useContext } from "react";
import SidebarItem from "./SidebarItem";
import { Icon } from "@iconify/react/dist/iconify.js";
import { signOut } from "../../firebase.config";
import AppContext from "../../AppContext";

const sidebarItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/edaa18958094e3996eae910d7142657c7aa719cbae587d9bc34ce856926dc206?apiKey=4c68bb9d73974fb3842275effd83c10f&",
    title: "控制面板",
    subtitle: "Dashboard",
  },

  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6fdd8213e21a3560a9eea36a62b42fc22d0b7430aa724c75e03c064306b37a99?apiKey=4c68bb9d73974fb3842275effd83c10f&",
    title: "管理班级",
    subtitle: "Manage Classes",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/96570de937efa17b8ac432aa49e6572ee979f105293714d47216b8cf710ea1ac?apiKey=4c68bb9d73974fb3842275effd83c10f&",
    title: "处理出缺席事宜",
    subtitle: "Manage Absences",
  },
  {
    icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgMjQgMjQiPjxwYXRoIGZpbGw9IndoaXRlIiBkPSJNMTMgNy41YTEgMSAwIDEgMS0yIDBhMSAxIDAgMCAxIDIgMG0tMyAzLjc1YS43NS43NSAwIDAgMSAuNzUtLjc1aDEuNWEuNzUuNzUgMCAwIDEgLjc1Ljc1djQuMjVoLjc1YS43NS43NSAwIDAgMSAwIDEuNWgtM2EuNzUuNzUgMCAwIDEgMC0xLjVoLjc1VjEyaC0uNzVhLjc1Ljc1IDAgMCAxLS43NS0uNzUiLz48cGF0aCBmaWxsPSJ3aGl0ZSIgZD0iTTEyIDFjNi4wNzUgMCAxMSA0LjkyNSAxMSAxMXMtNC45MjUgMTEtMTEgMTFTMSAxOC4wNzUgMSAxMlM1LjkyNSAxIDEyIDFNMi41IDEyYTkuNSA5LjUgMCAwIDAgOS41IDkuNWE5LjUgOS41IDAgMCAwIDkuNS05LjVBOS41IDkuNSAwIDAgMCAxMiAyLjVBOS41IDkuNSAwIDAgMCAyLjUgMTIiLz48L3N2Zz4=",
    title: "学生资料",
    subtitle: "Students Info",
  },
  {
    icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgMjQgMjQiPjxwYXRoIGZpbGw9IndoaXRlIiBkPSJNMTYgMTFjMS42NiAwIDIuOTktMS4zNCAyLjk5LTNTMTcuNjYgNSAxNiA1Yy0xLjY2IDAtMyAxLjM0LTMgM3MxLjM0IDMgMyAzbS04IDBjMS42NiAwIDIuOTktMS4zNCAyLjk5LTNTOS42NiA1IDggNUM2LjM0IDUgNSA2LjM0IDUgOHMxLjM0IDMgMyAzbTAgMmMtMi4zMyAwLTcgMS4xNy03IDMuNVYxOWgxNHYtMi41YzAtMi4zMy00LjY3LTMuNS03LTMuNW04IDBjLS4yOSAwLS42Mi4wMi0uOTcuMDVjMS4xNi44NCAxLjk3IDEuOTcgMS45NyAzLjQ1VjE5aDZ2LTIuNWMwLTIuMzMtNC42Ny0zLjUtNy0zLjUiLz48L3N2Zz4=",
    title: "出缺席统计",
    subtitle: "Attendance Statistics",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/22b0d36590de25f7916abf4378b02d23b3831678287b145063e3dbda5a2e794a?apiKey=4c68bb9d73974fb3842275effd83c10f&",
    title: "登出",
    subtitle: "Log Out",
    isLogout: true,
  },
];

const Sidebar: React.FC = () => {
  const { userData, navigate } = useContext<any>(AppContext);

  return (
    <aside className="flex flex-col shrink-0 w-3/12 bg-zinc-800/50 py-8 h-100">
      <div className="flex flex-col items-center pl-6 text-white max-md:pl-5">
        <div className="flex gap-2.5 items-center self-stretch font-semibold">
          <Icon icon="tabler:school" className="size-8" />
          <div className="flex flex-col">
            <div className="tracking-widest">新山宽柔中学</div>
            <div className="mt-1.5 text-xs tracking-wider">
              Foon Yew High School
            </div>
          </div>
        </div>
        <img
          loading="lazy"
          src={userData?.photoUrl}
          alt="User profile"
          referrerPolicy="no-referrer"
          className="mt-14 w-20 rounded-full aspect-square max-md:mt-10"
        />
        <div className="mt-6 text-2xl tracking-[2.64px] font-semibold">
          {userData?.ch_name}
        </div>
        <div className="mt-4 text-sm tracking-widest text-zinc-400">
          {userData?.role === "form_teacher"
            ? `${userData.class} 班主任`
            : "管理员"}
        </div>
      </div>
      <nav className="w-full mt-12">
        {sidebarItems.map((item, index) => (
          <button className="flex flex-col w-full text-left">
            {item.title === "登出" ? (
              <button
                onClick={() => {
                  signOut();
                  navigate("/login");
                }}
                className="w-full"
              >
                <SidebarItem key={index} {...item} />
              </button>
            ) : item.title == "管理班级" && userData?.role == "form_teacher" ? (
              <SidebarItem key={index} {...item} />
            ) : item.title == "处理出缺席事宜" &&
              userData?.role == "displin" ? (
              <SidebarItem key={index} {...item} />
            ) : item.title != "管理班级" && item.title != "处理出缺席事宜" ? (
              <SidebarItem key={index} {...item} />
            ) : null}
          </button>
        ))}
      </nav>
    </aside>
  );
};

export default Sidebar;
