/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { toLinkCase } from "../../utils/string";
import { Icon } from "@iconify/react/dist/iconify.js";
import { auth } from "../../firebase.config";
import { signOut } from "firebase/auth";

interface SidebarItemProps {
  icon: string;
  title: string;
  subtitle: string;
  isActive?: boolean;
  isLogout?: boolean;
}

const SidebarItem: React.FC<SidebarItemProps> = ({
  icon,
  title,
  subtitle,
  isLogout,
}) => {
  const navigate = useNavigate();
  const location = useLocation();
  const isActive = location.pathname.includes(toLinkCase(subtitle));

  const textColorClass = isActive
    ? "text-white"
    : isLogout
    ? "text-red-400"
    : "text-zinc-400";

  return title === "登出" ? (
    <button
      onClick={() => {
        signOut(auth)
          .then(() => {
            navigate("/login");
          })
          .catch((err) => {
            console.error(err);
          });
      }}
      className={`flex w-full gap-4 py-4 hover:bg-zinc-800 transition-all px-8 rounded-lg p-0.5 ${textColorClass}`}
    >
      <Icon icon={icon} className="size-6" />
      <div className="flex flex-col">
        <div className="tracking-widest">{title}</div>
        <div className="mt-2 text-sm tracking-wider">{subtitle}</div>
      </div>
    </button>
  ) : (
    <Link
      to={isLogout ? "" : `/${toLinkCase(subtitle)}`}
      className={`flex w-full gap-4 py-4 hover:bg-zinc-800 transition-all px-8 rounded-lg p-0.5 ${
        isActive &&
        "bg-blue-400/10 relative after:bg-blue-400 hover:bg-blue-500/20 after:right-0 after:top-1/2 after:-translate-y-1/2 after:h-1/2 after:w-1 after:absolute after:rounded-full"
      } ${textColorClass}`}
    >
      <Icon icon={icon} className="size-6" />
      <div className="flex flex-col">
        <div className="tracking-widest">{title}</div>
        <div className="mt-2 text-sm tracking-wider">{subtitle}</div>
      </div>
    </Link>
  );
};

export default SidebarItem;
