/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StudentListItem from "./StudentList";
import { StudentData } from "../../ManageAbsences/types";

interface StudentListProps {
  students: StudentData[];
}

const StudentList: React.FC<StudentListProps> = ({ students }) => {
  return (
    <div className="h-max overflow-auto">
      <div className="space-y-2 mt-4 mb-12 h-max overflow-auto">
        {students.map((student, index) => (
          <StudentListItem key={index} {...student} />
        ))}
      </div>
    </div>
  );
};

export default StudentList;
